export enum MainPalette {
  White = '#ffffff',
  DirtyWhite = '#F0F2F2',
  Grey = '#636766',
  LightBlue = '#E2F5FD',
  Blue = '#395B72',
  Charcoal = '#2C4251',
  Green = '#24B563',
  DarkGreen = '#109279',
  DarkRed = '#AD3546',
  Yellow = '#E9AD03',
}

export const IconsForUser = [
  'home',
  'basket',
  'pill',
  'clothes',
  'entertainment',
  'bus',
  'car',
  'bath',
  'rest',
  'work',
  'cake',
  'lamp',
  'laptop',
  'internet',
  'tv',
  'flower',
  'heart',
  'card-dollar',
  'card-euro',
  'creditcard',
  'money-multiple',
  'safe',
  'wallet',
];

export type ButtonType = 'primary' | 'secondary' | 'active' | 'inherit';
