export enum MainPalette {
  WHITE = '#ffffff',
  DIRTY_WHITE = '#F0F2F2',
  GREY = '#636766',
  LIGHT_BLUE = '#E2F5FD',
  BLUE = '#395B72',
  CHARCOAL = '#2C4251',
  GREEN = '#24B563',
  DARK_GREEN = '#109279',
  DARK_RED = '#AD3546',
  YELLOW = '#E9AD03',
}

export const IconsForUser = [
  'home',
  'basket',
  'pill',
  'clothes',
  'entertainment',
  'bus',
  'car',
  'bath',
  'rest',
  'work',
  'cake',
  'lamp',
  'laptop',
  'internet',
  'tv',
  'flower',
  'heart',
  'card-dollar',
  'card-euro',
  'creditcard',
  'money-multiple',
  'safe',
  'wallet',
];

export type ButtonType = 'primary' | 'secondary' | 'active' | 'inherit';
